---
# General Configuration
kube_domain: cluster.local
traefik_domain: example
letsencrypt_env: production
firewall: ufw
rke2_os: "linux"
home_path: /home/{{ ansible_user }}

# Pinned Releases
kube_vip_version: "v0.9.1"
rke2_install_dir: "/usr/local/bin"
rke2_version: "v1.33.3+rke2r1"
metallb_version: v0.15.2
helm_version: "v3.18.4"

# Install Options
kube_vip_noinstall: false
metallb_noinstall: false
certbot_noinstall: false
traefik_noinstall: false
disable_networkmanager: true
disable_firewalld: true
install_ufw_rules: true

# RKE Configuration Options
cni_plugin: canal
vip_interface: eth0
vip: 192.168.100.30
management_network: "192.168.100.0/24"
metallb_path: "{{ home_path }}/metallb"
lb_range: 192.168.100.240-192.168.100.254
lb_pool_name: first-pool

# Helm Options
kubectl_config: "{{ home_path }}/.kube/config"

# Cert-Manager Options
cert_manager_chart_ref: jetstack/cert-manager
# https://github.com/cert-manager/cert-manager/releases
cert_manager_chart_version: v1.18.2
cert_manager_path: "{{ home_path }}/cert-manager"
cert_manager_email: your_email@your_domain.com

# Traefik Options
traefik_chart_ref: traefik/traefik
# https://github.com/traefik/traefik-helm-chart/releases
traefik_chart_version: 37.0.0
traefik_path: "{{ home_path }}/traefik"
traefik_dashboard_expose: false

# Rancher Options
# https://github.com/rancher/rancher/releases
rancher_chart_ref: rancher-stable/rancher
rancher_chart_version: 2.12.0
rancher_path: "{{ home_path }}/rancher"

# Longhorn Options
longhorn_chart_ref: longhorn-stable/longhorn
longhorn_chart_version: 1.9.1
longhorn_path: "{{ home_path }}/longhorn"

# MySQL Operator Options
mysql_operator_chart_ref: mysql-operator/mysql-operator
mysql_operator_chart_version: "8.4.3"
mysql_operator_path: "{{ home_path }}/mysql-operator"

# Rook Ceph Options
rook_ceph_namespace: rook-ceph
rook_ceph_operator_chart_version: "1.17.7"
rook_ceph_min_device_capacity: "5Ti"
rook_ceph_version: "v18.2.2"
rook_ceph_mon_count: 3
rook_ceph_replica_size: 1
rook_ceph_pool_name: replicapool
rook_ceph_storage_class_name: rook-ceph-block
rook_ceph_make_storage_class_default: true
rook_ceph_enable_filesystem: false
rook_ceph_filesystem_name: "cephfs"
rook_ceph_fs_storage_class: "rook-cephfs"
rook_ceph_fs_make_default: false
rook_ceph_enable_objectstore: false
rook_ceph_objectstore_name: "ceph-objectstore"
rook_ceph_objectstore_storage_class: "rook-ceph-bucket"
rook_ceph_objectstore_gateway_port: 80
rook_ceph_objectstore_replicas: 1

# Component Installation Controls
rke2_install_metallb: true
rke2_install_kubevip: true
rook_install_operator: true
rook_install_cluster: true
mysql_install_operator: true

