---
kube_domain: example.com
letsencrypt_env: production

# Default versions
kube_vip_version: "v0.9.1"
vip_interface: "eth0"
rke2_install_dir: "/usr/local/bin"
rke2_version: "v1.33.1+rke2r1"
metallb_version: v0.15.2
helm_version: "3.18.2"

kube_vip_noinstall: false
metallb_noinstall: false
certbot_noinstall: false
traefik_noinstall: false

disable_networkmanager: true
disable_firewalld: true
install_ufw_rules: true

cni_plugin: canal

os: "linux"

vip: 192.168.100.30

metallb_path: "{{ home_path }}/metallb"
lb_range: 192.168.100.240-192.168.100.254
lb_pool_name: first-pool

kubectl_config: "{{ home_path }}/.kube/config"

cert_manager_chart_ref: jetstack/cert-manager
# https://github.com/cert-manager/cert-manager/releases
cert_manager_chart_version: v1.15.0
cert_manager_path: "{{ home_path }}/cert-manager"
cert_manager_email: your_email@your_domain.com

traefik_chart_ref: traefik/traefik
# https://github.com/traefik/traefik-helm-chart/releases
traefik_chart_version: 28.3.0
traefik_path: "{{ home_path }}/traefik"

# https://github.com/rancher/rancher/releases
rancher_chart_ref: rancher-alpha/rancher
rancher_chart_version: 2.9.0-alpha5
rancher_path: "{{ home_path }}/rancher"

minio_operator_path: "{{ home_path }}/minio-operator"
minio_operator_namespace: "minio_operator"

minio_tenant_path: "{{ home_path }}/minio-tenant"
minio_tenant_namespace: "minio_tenant"
minio_tenant_name: "minio"
# CSI driver can be "defaut" or "directpv-min-io"
minio_csi_driver_name: "directpv-min-io"
direct_pv_version: "4.1.5"

minio_root_user: "minio"
minio_root_password: "minio123"
minio_storage_class_standard: "EC:2"
minio_browser: "on"

console_access_key: "console"
console_secret_key: "console123"

minio_servers: 3
minio_volumes_per_server: 1
minio_storage_requests: "1Ti"