---
# Cloudflare API Token - Required for cert-manager DNS-01 ACME challenges
# Get this from: https://dash.cloudflare.com/profile/api-tokens
# Permissions needed: Zone:Zone:Read, Zone:DNS:Edit
cf_token: "your_cloudflare_token_here"
# ### Use ansible vault create to create the encrypted file.
