# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Deploy RKE2 server Configuration
  ansible.builtin.template:
    src: templates/rke2-server-config2.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname != groups['controllers'][0]

- name: Create systemd service file for RKE2 server
  ansible.builtin.template:
    src: templates/rke2-server.service.j2
    dest: /etc/systemd/system/rke2-server.service
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname != groups['controllers'][0]

- name: Ensure additional RKE2 controllers are enabled and running
  ansible.builtin.systemd:
    name: rke2-server
    enabled: true
    state: restarted
    daemon_reload: true
  when: inventory_hostname != groups['controllers'][0]
