# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Add RKE2 agents to cluster
  when: inventory_hostname in groups['agents']
  block:
    - name: Create systemd service file for RKE2 agent
      ansible.builtin.template:
        src: templates/rke2-agent.service.j2
        dest: /etc/systemd/system/rke2-agent.service
        owner: root
        group: root
        mode: "0644"

    - name: Deploy RKE2 Agent Configuration
      ansible.builtin.template:
        src: templates/rke2-agent-config.j2
        dest: /etc/rancher/rke2/config.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Ensure RKE2 agents are enabled and running
      ansible.builtin.systemd:
        name: rke2-agent
        enabled: true
        state: restarted
        daemon_reload: true
