# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Deploy RKE2 server Configuration
  ansible.builtin.template:
    src: templates/rke2-server-config2.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname != groups['controllers'][0]

- name: Create systemd service file for RKE2 server
  ansible.builtin.template:
    src: templates/rke2-server.service.j2
    dest: /etc/systemd/system/rke2-server.service
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname != groups['controllers'][0]

- name: Check RKE2 server service status before API check
  ansible.builtin.systemd:
    name: rke2-server
  register: rke2_service_status
  when: inventory_hostname == groups['controllers'][0]

- name: Display RKE2 service status for debugging
  ansible.builtin.debug:
    msg: "RKE2 service state: {{ rke2_service_status.status.ActiveState | default('unknown') }}"
  when: inventory_hostname == groups['controllers'][0]

- name: Wait for cluster API to be ready
  ansible.builtin.command:
    cmd: "kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get nodes"
  register: kubectl_output
  until: kubectl_output.rc == 0
  retries: 30
  delay: 10
  changed_when: false
  failed_when: false
  become: true
  when: inventory_hostname == groups['controllers'][0]

- name: Display kubectl output for debugging if failed
  ansible.builtin.debug:
    msg:
      - "kubectl return code: {{ kubectl_output.rc | default('undefined') }}"
      - "kubectl stdout: {{ kubectl_output.stdout | default('No output') }}"
      - "kubectl stderr: {{ kubectl_output.stderr | default('No error output') }}"
  when:
    - inventory_hostname == groups['controllers'][0]
    - kubectl_output is defined
    - kubectl_output.rc != 0

- name: Fail if cluster API is not ready after timeout
  ansible.builtin.fail:
    msg: >
      Cluster API failed to become ready after 5 minutes.
      Last kubectl output: {{ kubectl_output.stdout if kubectl_output.stdout else 'No output' }}
      Error: {{ kubectl_output.stderr if kubectl_output.stderr else 'No error output' }}
  when:
    - inventory_hostname == groups['controllers'][0]
    - kubectl_output is defined
    - kubectl_output.rc != 0

- name: Apply kube vip configuration file
  ansible.builtin.command:
    cmd: kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml apply -f https://kube-vip.io/manifests/rbac.yaml
  changed_when: true
  when: inventory_hostname == groups['controllers'][0]

- name: Apply kube vip configuration file
  ansible.builtin.command:
    cmd: >
      kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml apply -f
      https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml
  changed_when: true
  when: inventory_hostname == groups['controllers'][0]

- name: Ensure additional RKE2 controllers are enabled and running
  ansible.builtin.systemd:
    name: rke2-server
    enabled: true
    state: restarted
    daemon_reload: true
  when: inventory_hostname != groups['controllers'][0]
