# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for apply-manifests

# Prerequisites should be handled at playbook level or in a separate setup role
# The kubernetes.core.k8s module will fail with a clear error if the library is missing

- name: Metallb installation
  tags: metallb
  become: true
  become_user: "{{ ansible_user }}"
  when: inventory_hostname == groups['controllers'][0]
  block:
    - name: Create metallb directory
      ansible.builtin.file:
        path: "{{ metallb_path }}"
        mode: "0744"
        state: directory

    - name: Wait for k8s nodes with node label 'server=true' to be ready
      ansible.builtin.command:
        cmd: "kubectl wait --for=condition=Ready nodes --selector server=true --timeout=600s"
      changed_when: true

    - name: Apply metallb manifest
      ansible.builtin.command:
        cmd: >
          kubectl apply -f
          https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
      changed_when: true

    - name: Wait for metallb pods to be ready, otherwise we cannot start metallb deployment
      ansible.builtin.command:
        cmd: >
          kubectl wait --namespace metallb-system --for=condition=ready pod
          --selector=component=controller --timeout=1800s
      changed_when: true

    - name: Copy metallb L2Advertisement to server 1
      ansible.builtin.template:
        src: templates/l2Advertisement.yaml.j2
        dest: "{{ metallb_path }}/l2Advertisement.yaml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Copy metallb IPPool to server 1
      ansible.builtin.template:
        src: templates/metallb-ippool.j2
        dest: "{{ metallb_path }}/ippool.yaml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Apply metallb ipppool
      ansible.builtin.command:
        cmd: "kubectl apply -f {{ metallb_path }}/ippool.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
      changed_when: true

    - name: Apply metallb L2Advertisement
      ansible.builtin.command:
        cmd: "kubectl apply -f {{ metallb_path }}/l2Advertisement.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
      changed_when: true
