# SPDX-License-Identifier: GPL-3.0-or-later
---
# Remove NetworkManager per https://docs.rke2.io/install/methods
- name: Remove NetworkManager
  ansible.builtin.package:
    name: network-manager
    state: absent
  become: true
  when: disable_networkmanager

- name: Disable and stop firewalld if present
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  when: >
    ansible_facts.services is defined and
    'firewalld.service' in ansible_facts.services and
    ansible_facts.services['firewalld.service'].state == 'running'
  become: true

- name: Check for UFW and configure rules if present
  ansible.builtin.include_tasks:
    file: prepare-nodes-ufw.yaml
