# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Check if UFW is installed
  ansible.builtin.package_facts:
    manager: auto
  failed_when: false

- name: Configure common UFW rules for all nodes
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop: "{{ ufw_rules_common }}"
  notify: Reload UFW
  when:
    - ansible_facts.packages is defined
    - "'ufw' in ansible_facts.packages"
  become: true

- name: Configure additional UFW rules for controller nodes
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  loop: "{{ ufw_rules_controllers }}"
  notify: Reload UFW
  when:
    - inventory_hostname in groups['controllers']
    - ansible_facts.packages is defined
    - "'ufw' in ansible_facts.packages"
  become: true
