# SPDX-License-Identifier: GPL-3.0-or-later
---
# Remove NetworkManager per https://docs.rke2.io/install/methods
- name: Remove NetworkManager
  ansible.builtin.package:
    name: network-manager
    state: absent
  become: true
  when: disable_networkmanager

- name: Disable and stop firewalld if present
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  when: >
    ansible_facts.services is defined and
    'firewalld.service' in ansible_facts.services and
    ansible_facts.services['firewalld.service'].state == 'running'
  become: true

- name: Handle SELinux for RHEL-based systems
  when: ansible_os_family == "RedHat"
  become: true
  block:
    - name: Check SELinux status
      ansible.builtin.command: getenforce
      register: selinux_status
      changed_when: false
      failed_when: false

    - name: Install container-selinux package
      ansible.builtin.package:
        name: container-selinux
        state: present
      when: selinux_status.stdout == "Enforcing"

    - name: Set SELinux to permissive mode temporarily
      ansible.builtin.command: setenforce 0
      when: selinux_status.stdout == "Enforcing"
      changed_when: true

    - name: Ensure SELinux file contexts for RKE2
      ansible.builtin.command: |
        semanage fcontext -a -t container_file_t '/var/lib/rancher/rke2(/.*)?'
        restorecon -R /var/lib/rancher/rke2
      when: selinux_status.stdout != "Disabled"
      failed_when: false
      changed_when: false

- name: Check for UFW and configure rules if present
  ansible.builtin.include_tasks:
    file: prepare-nodes-ufw.yaml
