# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for longhorn_install

- name: Ensure Longhorn is installed
  tags: [longhorn, storage-longhorn]
  block:
    - name: Create longhorn directory
      ansible.builtin.file:
        path: "{{ longhorn_path }}"
        mode: "0744"
        state: directory

    - name: Add longhorn Helm repository
      kubernetes.core.helm_repository:
        name: longhorn-stable
        repo_url: https://charts.longhorn.io
        state: present
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
      when: not (skip_kubernetes_operations or skip_helm_operations)

    - name: Create longhorn namespace
      kubernetes.core.k8s:
        name: "{{ longhorn_namespace }}"
        api_version: v1
        kind: Namespace
        state: present
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
      when: not (skip_kubernetes_operations or skip_helm_operations)

    - name: Update the repository cache
      kubernetes.core.helm:
        name: dummy
        namespace: kube-system
        state: absent
        update_repo_cache: true
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
      when: not (skip_kubernetes_operations or skip_helm_operations)

    - name: Deploy longhorn chart inside {{ longhorn_namespace }} namespace
      kubernetes.core.helm:
        name: longhorn
        chart_ref: "{{ longhorn_chart_ref }}"
        chart_version: "{{ longhorn_chart_version }}"
        release_namespace: "{{ longhorn_namespace }}"
        create_namespace: true
        update_repo_cache: true
        state: present
        wait: true
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
      when: 
        - longhorn_install_system | default(true)
        - not (skip_kubernetes_operations or skip_helm_operations)

    - name: Display Longhorn configuration (test mode)
      ansible.builtin.debug:
        msg:
          - "Longhorn would be deployed with:"
          - "Chart: {{ longhorn_chart_ref }}"
          - "Version: {{ longhorn_chart_version }}"
          - "Namespace: {{ longhorn_namespace }}"
          - "Repository: https://charts.longhorn.io"
          - "Replica Count: {{ longhorn_replica_count }}"
          - "Storage Class: {{ longhorn_storage_class_name }}"
      when: skip_kubernetes_operations or skip_helm_operations