# SPDX-License-Identifier: GPL-3.0-or-later
---
# defaults file for deploy-rke2-cluster
kube_vip_version: "v0.9.1"
vip_interface: "eth0"
rke2_install_dir: "/usr/local/bin"
rke2_version: "v1.33.1+rke2r1"
metallb_version: v0.15.2

kube_vip_noinstall: false
metallb_noinstall: false

disable_networkmanager: true
# Options are 'ufw' or 'calico'
firewall: ufw

cni_plugin: canal

os: "linux"

vip: 192.168.100.30


lb_range: 192.168.100.240-192.168.100.254
lb_pool_name: first-pool

supported_os_versions:
  SLES:
    - "15 SP6"
    - "15 SP5"
    - "15 SP4"
    - "15 SP3"
  Oracle:
    - "9.5"
    - "9.4"
    - "9.3"
    - "9.2"
    - "8.10"
    - "8.9"
    - "8.8"
  RedHat:
    - "9.5"
    - "9.4"
    - "9.3"
    - "9.2"
    - "8.10"
    - "8.9"
    - "8.8"
    - "8.7"
  Rocky:
    - "9.5"
    - "9.4"
    - "9.3"
    - "9.2"
    - "8.10"
    - "8.9"
    - "8.8"
    - "8.7"
  Amazon:
    - "2"
    - "2023"
  Ubuntu:
    - "25.04"
    - "24.04"
    - "22.04"
    - "20.04"
