# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Create self-signed ClusterIssuer
  tags: cert-manager
  block:
    - name: Create cert-manager directory
      ansible.builtin.file:
        path: "{{ cert_manager_path }}"
        mode: "0744"
        state: directory

    - name: Copy ClusterIssuer file to master node
      ansible.builtin.template:
        src: selfsigned-root-clusterissuer.yaml.j2
        dest: "{{ cert_manager_path }}/selfsigned-root-clusterissuer.yaml"
        mode: "0644"

    - name: Create ClusterIssuer
      kubernetes.core.k8s:
        state: present
        src: "{{ cert_manager_path }}/selfsigned-root-clusterissuer.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

- name: Create CA Issuer for minio-Operator
  tags: cert-manager
  block:
    - name: Create namespace if it doesn't exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ minio_operator_namespace }}"
        state: present
    - name: Request certificate
      block:
          - name: Copy certificate spec to master node
            ansible.builtin.template:
              src: operator-ca-tls-secret.yaml.j2
              dest: "{{ cert_manager_path }}/operator-ca-tls-secret.yaml"
              mode: "0644"
          - name: Create certificate
            kubernetes.core.k8s:
              state: present
              src: "{{ cert_manager_path }}/operator-ca-tls-secret.yaml"
            environment:
              KUBECONFIG: "{{ kubectl_config }}"
    - name: Create the Issuer
      block:
          - name: Copy Issuer spec to master node
            ansible.builtin.template:
              src: operator-ca-issuer.yaml.j2
              dest: "{{ cert_manager_path }}/operator-ca-issuer.yaml"
              mode: "0644"
          - name: Create Issuer
            kubernetes.core.k8s:
              state: present
              src: "{{ cert_manager_path }}/operator-ca-issuer.yaml"
- name: Create TLS certificate
  tags: cert-manager
  block:
    - name: Copy Certificate spec to master node
      ansible.builtin.template:
        src: sts-tls-certificate.yaml.j2
        dest: "{{ cert_manager_path }}/sts-tls-certificate.yaml"
        mode: "0644"
    - name: Create certificate
      kubernetes.core.k8s:
        state: present
        src: "{{ cert_manager_path }}/sts-tls-certificate.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}"