# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install direct-pv binary on master node
  ansible.builtin.get_url:
    url: https://github.com/minio/directpv/releases/download/v{{direct_pv_version}}/kubectl-directpv_{{direct_pv_version}}_linux_amd64
    dest: /home/{{ ansible_user }}/.local/bin/kubectl-directpv
    mode: a+x
  tags: direct-pv

- name: Pause for user input
  pause:
    prompt: |
      The Direct PV binary has been install at ~/.local/bin/kubectl-directpv

      <<< CONFIGURING DISKS IS DESTRUCTIVE >>
      The playbook will not do it automatically.  To proceed:
      
      1. cd ~/minio
      2. kubectl-directpv install # installs directpv to all nodes
      3. kubectl-directpv discover
      4. Edit the "drives.yaml" file created in your current working directory
      5. For ALL drives, ensure nodes.drives.select is "no"
      6. For the drives you want to add, go back and mark "yes" under nodes.drives.select
      7. WARNING:  The next step will reformat the drives.... be careful
      7. kubectl-directpv init drives.yaml

      If all goes well, enter "yes" to proceed; CTRL+C and A to abort...

  register: user_response

- name: Continue with playbook
  ansible.builtin.debug:
    msg: "User chose to continue"
  when: user_response.user_input == "yes"

