# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Install direct-pv binary on master node
  ansible.builtin.get_url:
    url: https://github.com/minio/directpv/releases/download/v{{direct_pv_version}}/kubectl-directpv_{{direct_pv_version}}_linux_amd64
    dest: /home/{{ ansible_user }}/.local/bin/kubectl-directpv
    mode: a+x
  tags: direct-pv

- name: Pause for user input
  pause:
    prompt: |
      The Direct PV binary has been install at ~/.local/bin/kubectl-directpv

      <<< CONFIGURING DISKS IS DESTRUCTIVE >>
      The playbook will not do it automatically.  To proceed:
      
      1. kubectl-directpv install # installs directpv to all nodes
      2. kubectl-directpv discover
      3. Edit the "drives.yaml" file created in your current working directory
      4. For the drives you do not want formatted (all data lost), delete the entire entry for them (safest),
         or mark "no" under nodes.drive.select
      5. The remaining drives are marked "yes" under nodes.drives.select - directpv will reformat them
      WARNING:  The next step will reformat the drives.... be careful
      6. kubectl-directpv init drives.yaml --dangerous

      If all goes well, enter "yes" to proceed; CTRL+C and A to abort...

  register: user_response

- name: Continue with playbook
  ansible.builtin.debug:
    msg: "User chose to continue"
  when: user_response.user_input == "yes"

