- name: Deploy minio-operator
  tags: minio-operator
  block:
    - name: Ensure namespace is present
      kubernetes.core.k8s:
        name: "{{ minio_operator_namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Create minio-tenant directory
      ansible.builtin.file:
        path: "{{ minio_tenant_path }}"
        mode: "0744"
        state: directory

    - name: Copy files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "0644"
      loop:
        - src: tenant-base.yaml.j2
          dest: "{{ minio_tenant_path }}/tenant-base.yaml"
        - src: certificate-wildcard-minio.yaml.j2
          dest: "{{ minio_tenant_path }}/certificate-wildcard-minio.yaml"
        - src: traefik-ingress-minio-api.yaml.j2
          dest: "{{ minio_tenant_path }}/traefik-ingress-minio-api.yaml"
        - src: traefik-ingress-minio-console.yaml.j2
          dest: "{{ minio_tenant_path }}/traefik-ingress-minio-console.yaml"

    - name: Deploy tenant
      kubernetes.core.k8s:
        state: present
        src: "{{ minio_tenant_path }}/tenant-base.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

    - name: Create the certificate
      kubernetes.core.k8s:
        state: present
        src: "{{ minio_tenant_path }}/certificate-wildcard-minio.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

    - name: Create the ingresses for API and Console
      kubernetes.core.k8s:
        state: present
        src: "{{ item }}"
      loop:
        - "{{ minio_tenant_path }}/traefik-ingress-minio-api.yaml"
        - "{{ minio_tenant_path }}/traefik-ingress-minio-console.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

- name: Ensure UFW is installed
  ansible.builtin.package:
    name: ufw
    state: present
  become: true

- name: Ensure UFW rules are present for minio
  community.general.ufw:
    rule: allow
    port: 9000
    proto: any
    comment: minio
  notify: Reload UFW
  become: true