- name: Deploy minio-operator
  tags: minio-operator
  block:
    - name: Ensure namespace is present
      kubernetes.core.k8s:
        name: "{{ minio_operator_namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Create minio-tenant directory
      ansible.builtin.file:
        path: "{{ minio_tenant_path }}"
        mode: "0744"
        state: directory

    - name: Copy base spec
      ansible.builtin.template:
        src: tenant-base.yaml.j2
        dest: "{{ minio_operator_path }}/tenant-base.yaml"
        mode: "0644"

    - name: Deploy tenant
      kubernetes.core.k8s:
        state: present
        src: "{{ cert_manager_path }}/tenant-base.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}"