# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Ensure Helm binary is available
  tags: helm
  block:
    - name: Install required dependencies for Helm installation (Debian/Ubuntu)
      ansible.builtin.apt:
        name:
          - curl
          - git
        state: present
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"

    - name: Install required dependencies for Helm installation (RedHat/CentOS)
      ansible.builtin.dnf:
        name:
          - curl
          - git
        state: present
      become: true
      when: ansible_os_family == "RedHat"

    - name: Install required dependencies for Helm installation (SUSE)
      community.general.zypper:
        name:
          - curl
          - git
        state: present
      become: true
      when: ansible_os_family == "Suse"

    - name: Ensure user-local bin directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: '0755'

    - name: Download Helm installer script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: "{{ ansible_env.HOME }}/get-helm-3.sh"
        mode: '0755'
        force: false

    - name: Install Helm
      ansible.builtin.command: >
        bash {{ ansible_env.HOME }}/get-helm-3.sh
      environment:
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
      args:
        creates: /usr/local/bin/helm

    - name: Ensure helm binary is executable
      ansible.builtin.file:
        path: /usr/local/bin/helm
        mode: '0755'
      become: true

    - name: Create helm data & plugin dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: '0755'
      loop:
        - "{{ ansible_user_dir }}/.local/share/helm"
        - "{{ ansible_user_dir }}/.local/share/helm/plugins"

- name: Check if Helm Diff plugin is installed
  ansible.builtin.command: /usr/local/bin/helm plugin list
  register: helm_plugins
  changed_when: false
  failed_when: false
  tags: helm-diff

- name: Install Helm Diff plugin
  ansible.builtin.command: >
    /usr/local/bin/helm plugin install https://github.com/databus23/helm-diff
  when: "'diff' not in helm_plugins.stdout"
  changed_when: true
  tags: helm-diff

- name: Install pip/python requirements for Kubernetes (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-kubernetes
    state: present
    update_cache: true
  become: true
  when:
    - ansible_os_family == "Debian"
    - inventory_hostname in groups['controllers']
  tags: python3-kubernetes

- name: Install pip/python requirements for Kubernetes (RedHat/CentOS/Rocky)
  ansible.builtin.dnf:
    name:
      - python3-pip
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - inventory_hostname in groups['controllers']
  tags: python3-kubernetes

- name: Install Kubernetes Python library via pip (RedHat/CentOS/Rocky)
  ansible.builtin.pip:
    name: kubernetes
    state: present
  become: true
  when:
    - ansible_os_family == "RedHat"
    - inventory_hostname in groups['controllers']
  tags: python3-kubernetes

- name: Install pip/python requirements for Kubernetes (SUSE)
  community.general.zypper:
    name:
      - python3-pip
      - python3-kubernetes
    state: present
  become: true
  when:
    - ansible_os_family == "Suse"
    - inventory_hostname in groups['controllers']
  tags: python3-kubernetes

- name: Install Kubernetes Python library via pip (fallback)
  ansible.builtin.pip:
    name: kubernetes
    state: present
  become: true
  when:
    - ansible_os_family not in ["Debian", "RedHat", "Suse"]
    - inventory_hostname in groups['controllers']
  tags: python3-kubernetes
