# SPDX-License-Identifier: GPL-3.0-or-later
---
extends: default

rules:
  line-length:
    max: 120
    level: warning

  comments-indentation: disable
  comments:
    min-spaces-from-content: 1

  document-start:
    present: true

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  commas:
    max-spaces-before: 0
    max-spaces-after: 1

  empty-lines:
    max: 2
    max-start: 0
    max-end: 1

  hyphens:
    max-spaces-after: 1

  key-duplicates: enable
  new-line-at-end-of-file: enable
  octal-values: enable
  trailing-spaces: enable

ignore: |
  .cache/
  .git/
  .gitlab-ci/
  .tox/
  .venv/
  molecule/
  .vagrant/
  *.tar.gz
  changelogs/fragments/
  tests/output/
