#!/usr/bin/env python3
import yaml
import glob
import re

def fix_meta_indentation(file_path):
    """Fix indentation issues in meta/main.yml files"""
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Fix common indentation patterns in YAML files generated by our script
    lines = content.split('\n')
    fixed_lines = []
    
    for line in lines:
        # Fix platforms section indentation
        if line.strip().startswith('platforms:'):
            fixed_lines.append('  platforms:')
        elif line.strip().startswith('- name:') and 'platforms:' in ''.join(lines):
            fixed_lines.append('  - name: ' + line.split('name:', 1)[1].strip())
        elif line.strip().startswith('versions:') and any('- name:' in prev_line for prev_line in lines):
            fixed_lines.append('    versions:')
        elif line.strip().startswith('- ') and any('versions:' in prev_line for prev_line in lines[-5:]):
            # Version items under versions
            fixed_lines.append('    - ' + line.split('- ', 1)[1])
        elif line.strip().startswith('galaxy_tags:'):
            fixed_lines.append('  galaxy_tags:')
        elif line.strip().startswith('dependencies:'):
            fixed_lines.append('dependencies: []')
        else:
            fixed_lines.append(line)
    
    with open(file_path, 'w') as f:
        f.write('\n'.join(fixed_lines))

def fix_task_files():
    """Fix specific task file issues"""
    # Fix colon spacing in teardown/tasks/main.yml
    teardown_file = 'roles/teardown/tasks/main.yml'
    try:
        with open(teardown_file, 'r') as f:
            content = f.read()
        # Fix "cmd  :" to "cmd:"
        content = re.sub(r'cmd\s*:\s+', 'cmd: ', content)
        with open(teardown_file, 'w') as f:
            f.write(content)
        print(f"Fixed colon spacing in {teardown_file}")
    except FileNotFoundError:
        print(f"File {teardown_file} not found")
    
    # Fix indentation in cert-manager files
    cert_files = [
        'roles/minio_install/tasks/cert-manager-operator.yaml',
        'roles/minio_install/tasks/cert-manager-tenant.yaml'
    ]
    
    for cert_file in cert_files:
        try:
            with open(cert_file, 'r') as f:
                lines = f.readlines()
            
            fixed_lines = []
            for line in lines:
                # Fix common indentation issues
                if re.match(r'^\s{10}', line):  # 10 spaces to 8
                    fixed_lines.append(line[2:])
                elif re.match(r'^\s{6}[^-]', line) and not re.match(r'^\s{6}-', line):  # 6 spaces to 8 for non-list items
                    fixed_lines.append('  ' + line)
                elif re.match(r'^\s{2}[^-\s]', line):  # 2 spaces to 4 for non-list items
                    fixed_lines.append('  ' + line)
                else:
                    fixed_lines.append(line)
            
            with open(cert_file, 'w') as f:
                f.writelines(fixed_lines)
            print(f"Fixed indentation in {cert_file}")
        except FileNotFoundError:
            print(f"File {cert_file} not found")

# Fix meta files
meta_files = glob.glob("roles/*/meta/main.yml")
for meta_file in meta_files:
    print(f"Fixing indentation in {meta_file}")
    fix_meta_indentation(meta_file)

# Fix task files
fix_task_files()
print("Fixed remaining YAML indentation and formatting issues")