# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Converge
  hosts: all
  tasks:
    - name: "Include longhorn_install role"
      ansible.builtin.include_role:
        name: "wolskinet.rke2_ansible.longhorn_install"
