# SPDX-License-Identifier: GPL-3.0-or-later
---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: longhorn-k8s
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    groups:
      - controllers
      - rke2

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: root
        # Longhorn configuration
        longhorn_chart_version: "1.9.1"
        longhorn_namespace: "longhorn-system"
        longhorn_path: "/root/longhorn"
        
        # Test mode overrides
        test_mode: true
        skip_kubernetes_operations: true
        skip_helm_operations: true
        
        # Component installation flags
        longhorn_install_system: true
        
        # Required for Helm dependency
        helm_version: "v3.18.4"
  
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      stdout_callback: yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy