# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if Helm is available
      ansible.builtin.command: helm version --short
      register: helm_check
      changed_when: false

    - name: Verify Helm is working
      ansible.builtin.assert:
        that:
          - helm_check.rc == 0
        fail_msg: "Helm is not available for MySQL Operator installation"
        success_msg: "Helm is available for MySQL Operator"

    - name: Test mode verification
      ansible.builtin.debug:
        msg: "Longhorn role completed in test mode - Kubernetes operations were skipped"
      when: true
