# SPDX-License-Identifier: GPL-3.0-or-later
---
galaxy_info:
  role_name: mysql_operator
  author: Ed Wolski
  description: Deploy MySQL Operator for Kubernetes database management
  company: wolskinet
  license: GPL-3.0-or-later
  min_ansible_version: "2.12"
  
  platforms:
    - name: Ubuntu
      versions:
        - "24.04"
        - "22.04"
        - "20.04"
    - name: Debian
      versions:
        - "12"
        - "11"
    - name: RedHat
      versions:
        - "9"
        - "8"
    - name: Rocky
      versions:
        - "9"
        - "8"
  
  galaxy_tags:
    - database
    - mysql
    - operator
    - kubernetes
    - sql
    - persistence
    - cluster
    - helm
    - container
    - automation
    - devops
    - infrastructure
    - oracle
    - innodb

dependencies:
  - role: wolskinet.rke2_ansible.helm_install
    when: ansible_os_family != "Windows"