# SPDX-License-Identifier: GPL-3.0-or-later
---
# handlers file for deploy-rke2-cluster
- name: Reload UFW
  become: true
  community.general.ufw:
    state: reloaded
  failed_when: false

- name: Reboot if SELinux changed
  ansible.builtin.reboot:
    msg: "Rebooting due to SELinux configuration change"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 5
    post_reboot_delay: 30
  become: true
