# SPDX-License-Identifier: GPL-3.0-or-later
---
# defaults file for mysql_operator

# General Configuration
home_path: /home/{{ ansible_user }}
traefik_domain: example

# Kubectl Options
kubectl_config: "{{ home_path }}/.kube/config"

# MySQL Operator Options
mysql_operator_chart_ref: mysql-operator/mysql-operator
mysql_operator_chart_version: "8.4.3"
mysql_operator_path: "{{ home_path }}/mysql-operator"

