# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for cert-manager
- name: Ensure Cert-Manager is installed
  tags: cert-manager
  block:
    - name: Create cert-manager directory
      ansible.builtin.file:
        path: "{{ cert_manager_path }}"
        mode: "0744"
        state: directory

    - name: Copy clusterissuer-letsencrypt-cloudflare-{{ letsencrypt_env }}.yaml to the master node
      ansible.builtin.template:
        src: clusterissuer-letsencrypt-cloudflare.yaml.j2
        dest: "{{ cert_manager_path }}/clusterissuer-letsencrypt-cloudflare-{{ letsencrypt_env }}.yaml"
        mode: "0644"

    - name: Add Cert-Manager Helm repository
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io
        state: present
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

    - name: Check if namespace exists
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: cert-manager
      register: namespace_info

    - name: Create namespace if it doesn't exist
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: cert-manager
        state: present
      when: namespace_info.resources is not defined

    - name: Deploy Cert-Manager chart inside cert-manager namespace
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: "{{ cert_manager_chart_ref }}"
        chart_version: "{{ cert_manager_chart_version }}"
        release_namespace: cert-manager
        update_repo_cache: true
        create_namespace: true
        state: present
        wait: true
        values:
          installCRDs: true
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

    - name: Create Cert-Manager Issuer
      kubernetes.core.k8s:
        state: present
        src: "{{ cert_manager_path }}/clusterissuer-letsencrypt-cloudflare-{{ letsencrypt_env }}.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
