# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for longhorn
- name: Ensure Longhorn is installed
  tags: longhorn
  block:
    - name: Create longhorn directory
      ansible.builtin.file:
        path: "{{ longhorn_path }}"
        mode: "0744"
        state: directory

    - name: Copy certificate-wildcard-longhorn.yaml to master node
      ansible.builtin.template:
        src: certificate-wildcard-longhorn.yaml.j2
        dest: "{{ longhorn_path }}/certificate-wildcard-longhorn.yaml"
        mode: "0644"

    - name: Add longhorn Helm repository
      kubernetes.core.helm_repository:
        name: longhorn-stable
        repo_url: https://charts.longhorn.io
        state: present
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

    - name: Create longhorn namespace
      kubernetes.core.k8s:
        name: longhorn-system
        api_version: v1
        kind: Namespace
        state: present
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

    # Accessing Longhorn UI via Rancher doesn't require cert
    # - name: Create wildcard certificate for longhorn
    #   kubernetes.core.k8s:
    #     state: present
    #     src: "{{ longhorn_path }}/certificate-wildcard-longhorn.yaml"
    #   environment:
    #     KUBECONFIG: "{{ kubectl_config }}"

    - name: Update the repository cache
      kubernetes.core.helm:
        name: dummy
        namespace: kube-system
        state: absent
        update_repo_cache: true
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

    - name: Deploy longhorn chart inside longhorn-system namespace
      kubernetes.core.helm:
        name: longhorn
        chart_ref: "{{ longhorn_chart_ref }}"
        chart_version: "{{ longhorn_chart_version }}"
        release_namespace: longhorn-system
        create_namespace: true
        update_repo_cache: true
        state: present
        wait: true
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
