# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for main.yaml
- name: Install Cert-Manager
  ansible.builtin.include_tasks:
    file: cert-manager.yaml
  tags: cert-manager
  when: rke2_install_certbot

# Not required if using RKE2's native ingress
- name: Configure Traefik
  ansible.builtin.include_tasks:
    file: traefik.yaml
  tags: traefik
  when: rke2_install_traefik

- name: Install Rancher
  ansible.builtin.include_tasks:
    file: rancher.yaml
  tags: rancher
