# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for main.yaml
- name: Ensure Helm binary is available
  ansible.builtin.include_tasks:
    file: prereqs.yaml
  tags:
    - helm
    - helm-diff
    - python3-kubernetes

- name: Install Cert-Manager
  ansible.builtin.include_tasks:
    file: cert-manager.yaml
  tags: cert-manager

- name: Configure Traefik
  ansible.builtin.include_tasks:
    file: traefik.yaml
  tags: traefik

- name: Install Rancher
  ansible.builtin.include_tasks:
    file: rancher.yaml
  tags: rancher

- name: Install Longhorn
  ansible.builtin.include_tasks:
    file: longhorn.yaml
  tags: longhorn
