# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for rancher_install
- name: Ensure user-local bin directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Download Helm installer script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: "{{ ansible_env.HOME }}/get-helm-3.sh"
    mode: '0755'
  args:
    creates: "{{ ansible_env.HOME }}/get-helm-3.sh"

- name: Install Helm into ~/.local/bin without sudo
  ansible.builtin.command: >
    bash {{ ansible_env.HOME }}/get-helm-3.sh --no-sudo
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/helm"
  environment:
    HELM_INSTALL_DIR: "{{ ansible_env.HOME }}/.local/bin"
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

- name: Ensure Helm Diff plugin is installed
  ansible.builtin.command: /usr/local/bin/helm plugin install https://github.com/databus23/helm-diff
  args:
    creates: "{{ ansible_env.HOME }}/.local/share/helm/plugins/helm-diff"
  environment:
    HELM_PLUGINS: "{{ ansible_env.HOME }}/.local/share/helm/plugins"
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"

- name: Install pip/python requirements for Kubernetes
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-kubernetes
    state: present
  become: true

- name: Install Cert-Manager
  ansible.builtin.include_tasks:
    file: cert-manager.yaml

- name: Install Traefik
  ansible.builtin.include_tasks:
    file: traefik.yaml

- name: Create rancher directory
  ansible.builtin.file:
    path: "{{ rancher_path }}"
    mode: '0744'  # Set directory permissions
    state: directory  # Ensure the directory exists

- name: Copy values.yaml to master node
  ansible.builtin.template:
    src: values.yaml-rancher.j2
    dest: "{{ rancher_path }}/values.yaml"
    mode: '0644'  # Set file permissions

- name: Copy certificate-wildcard-rancher.yaml to master node
  ansible.builtin.template:
    src: certificate-wildcard-rancher.yaml.j2
    dest: "{{ rancher_path }}/certificate-wildcard-rancher.yaml"
    mode: '0644'  # Set file permissions

- name: Add Rancher Helm repository
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable
    state: present  # Ensure the repository is added
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Create Rancher namespace
  kubernetes.core.k8s:
    name: cattle-system
    api_version: v1
    kind: Namespace
    state: present  # Ensure the namespace exists
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Create wildcard certificate for Rancher
  kubernetes.core.k8s:
    state: present
    src: "{{ rancher_path }}/certificate-wildcard-rancher.yaml"
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true  # Update the Helm repo cache
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable

- name: Deploy Rancher chart inside cattle-system namespace
  kubernetes.core.helm:
    name: rancher
    chart_ref: "{{ rancher_chart_ref }}"
    chart_version: "{{ rancher_chart_version }}"
    release_namespace: cattle-system
    create_namespace: true
    update_repo_cache: true
    state: present
    wait: true
    values:
      devel: false
    values_files:
      - "{{ rancher_path }}/values.yaml"  # Use values from the specified file
  environment:
    KUBECONFIG: "{{ kubectl_config }}"  # Use the kubectl config environment variable
