# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Ensure Helm binary is available
  tags: helm
  block:
    - name: Ensure user-local bin directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: '0755'

    - name: Download Helm installer script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: "{{ ansible_env.HOME }}/get-helm-3.sh"
        mode: '0755'
        force: false

    - name: Install Helm
      ansible.builtin.command: >
        bash {{ ansible_env.HOME }}/get-helm-3.sh
      args:
        creates: /usrlocal/bin/helm

    - name: Ensure helm binary is executable
      ansible.builtin.file:
        path: /usr/local/bin/helm
        mode: '0755'
      become: true

    - name: Create helm data & plugin dirs
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: '0755'
      loop:
        - "{{ ansible_user_dir }}/.local/share/helm"
        - "{{ ansible_user_dir }}/.local/share/helm/plugins"

- name: Install Helm Diff plugin
  ansible.builtin.command: >
    /usr/local/bin/helm plugin install https://github.com/databus23/helm-diff
  args:
    creates: "{{ ansible_user_dir }}/.local/share/helm/plugins/helm-diff"
  tags: helm-diff

- name: Install pip/python requirements for Kubernetes
  ansible.builtin.package:
    name:
      - python3-pip
      - python3-kubernetes
    state: present
  become: true
  tags: python3-kubernetes
