# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Ensure traefik is installed
  tags: traefik
  block:
    - name: Create traefik directory
      ansible.builtin.file:
        path: "{{ traefik_path }}"
        mode: "0744"
        state: directory

    - name: Copy values.yaml to master node
      ansible.builtin.template:
        src: values.yaml-traefik.j2
        dest: "{{ traefik_path }}/values.yaml"
        mode: "0644"

    - name: Copy certificate-wildcard-traefik.yaml to master node
      ansible.builtin.template:
        src: certificate-wildcard.yaml.j2
        dest: "{{ traefik_path }}/certificate-wildcard.yaml"
        mode: "0644"

    - name: Create wildcard certificate for Traefik
      kubernetes.core.k8s:
        state: present
        src: "{{ traefik_path }}/certificate-wildcard.yaml"
      environment:
        KUBECONFIG: "{{ kubectl_config }}" 
      tags: traefik

    - name: Add Traefik Helm repository
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: https://helm.traefik.io/traefik
        state: present
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

    - name: Create Traefik namespace
      kubernetes.core.k8s:
        name: traefik
        api_version: v1
        kind: Namespace
        state: present
      environment:
        KUBECONFIG: "{{ kubectl_config }}"

    - name: Deploy Traefik chart inside traefik namespace
      kubernetes.core.helm:
        name: traefik
        chart_ref: "{{ traefik_chart_ref }}"
        release_namespace: traefik
        create_namespace: true
        update_repo_cache: true
        state: present
        wait: true
        values_files:
          - "{{ traefik_path }}/values.yaml" 
      environment:
        KUBECONFIG: "{{ kubectl_config }}" 
