# SPDX-License-Identifier: GPL-3.0-or-later
---
galaxy_info:
  role_name: rook_install
  author: Ed Wolski
  description: >
    Deploy Rook Ceph storage operator with cluster, filesystem, and object store support
  company: wolskinet
  license: GPL-3.0-or-later
  min_ansible_version: "2.12"

  platforms:
    - name: Ubuntu
      versions:
        - noble
        - jammy
        - focal
    - name: Debian
      versions:
        - bookworm
        - buster
    - name: EL
      versions:
        - "9"
        - "8"
    - name: Rocky
      versions:
        - "9.2"
        - "8.8"
        - "8.7"
    - name: OracleLinux
      versions:
        - "9.4"
        - "9.3"
        - "9.2"
        - "8.10"
        - "8.9"
        - "8.8"
    - name: SLES
      versions:
        - "15SP6"
        - "15SP5"
        - "15SP4"
        - "15SP3"
    - name: Amazon
      versions:
        - all

  galaxy_tags:
    - storage
    - ceph
    - rook
    - kubernetes
    - operator
    - filesystem
    - objectstore
    - persistent
    - cluster
    - helm
    - container
    - automation
    - devops
    - infrastructure
    - backup
    - data
    - block
    - distributed

dependencies:
  - role: wolskinet.rke2_ansible.helm_install
    when: ansible_os_family != "Windows"
