# SPDX-License-Identifier: GPL-3.0-or-later
---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: rancher-k8s
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    groups:
      - controllers
      - rke2

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: root
        # Rancher configuration
        rancher_hostname: "rancher.test.local"
        cert_manager_email: "admin@test.local"
        letsencrypt_env: "staging"
        rancher_bootstrap_password: "test-password-123"

        # Component versions
        rancher_version: "2.11.3"
        cert_manager_version: "v1.17.2"
        traefik_version: "32.1.1"
        longhorn_version: "1.8.1"

        # Test mode overrides
        skip_rancher_installation: true
        skip_cert_manager_installation: true
        skip_traefik_installation: true
        skip_longhorn_installation: true
        test_mode: true

        # Component installation flags
        rke2_install_certbot: true
        rke2_install_traefik: true
        rancher_install_platform: false
        longhorn_install_system: false

        # Required for Helm dependency
        helm_version: "v3.18.4"

  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      stdout_callback: yaml
    ssh_connection:
      pipelining: false

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
