# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Prepare
  hosts: all
  become: true
  
  tasks:
    - name: Install Helm (dependency)
      ansible.builtin.include_role:
        name: wolskinet.rke2_ansible.helm_install

    - name: Create mock kubectl
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          echo "Mock kubectl: $@"
          case "$1" in
            get)
              if [[ "$*" == *"namespace"* ]]; then
                echo "NAME          STATUS   AGE"
                echo "kube-system   Active   1d"
                echo "default       Active   1d"
              else
                echo "Mock resource found"
              fi
              exit 0
              ;;
            apply|create)
              echo "Mock resource created"
              exit 0
              ;;
            delete)
              echo "Mock resource deleted"
              exit 0
              ;;
            wait)
              echo "Mock wait completed"
              exit 0
              ;;
            *)
              exit 0
              ;;
          esac
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Create kubeconfig directory
      ansible.builtin.file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'

    - name: Create mock kubeconfig
      ansible.builtin.copy:
        content: |
          apiVersion: v1
          clusters:
          - cluster:
              server: https://127.0.0.1:6443
            name: default
          contexts:
          - context:
              cluster: default
              user: default
            name: default
          current-context: default
          kind: Config
          users:
          - name: default
            user:
              token: mock-token
        dest: /etc/rancher/rke2/rke2.yaml
        mode: '0600'