# SPDX-License-Identifier: GPL-3.0-or-later
---
home_path: /home/{{ ansible_user }}
traefik_domain: example

kubectl_config: "{{ home_path }}/.kube/config"

# https://github.com/helm/helm/releases
helm_version: v3.18.2
