# SPDX-License-Identifier: GPL-3.0-or-later
---
# defaults file for helm_install

# General Configuration
home_path: /home/{{ ansible_user }}

# Helm Options
# https://github.com/helm/helm/releases
helm_version: "v3.18.4"
