# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Run Rook Ceph preflight checks
  ansible.builtin.include_tasks: rook_prereqs.yaml
  tags: [rook-prereqs, storage-rook]

- name: Install Rook Ceph operator via Helm
  ansible.builtin.include_tasks: rook_operator.yaml
  tags: [rook-operator, storage-rook]
  when: rook_install_operator | default(true)

- name: Deploy Rook CephCluster and default block storage
  ansible.builtin.include_tasks: rook_cluster.yaml
  tags: [rook-cluster, storage-rook]
  when: rook_install_cluster | default(true)

- name: Deploy Rook CephFilesystem and StorageClass (if enabled)
  ansible.builtin.include_tasks: rook_filesystem.yaml
  tags: [rook-filesystem, storage-rook]
  when: rook_ceph_enable_filesystem | default(false)

- name: Deploy Rook CephObjectStore and bucket provisioning (if enabled)
  ansible.builtin.include_tasks: rook_objectstore.yaml
  tags: [rook-objectstore, storage-rook]
  when: rook_ceph_enable_objectstore | default(false)
