# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Deploy CephObjectStore and optional bucket StorageClass
  block:

    - name: Create CephObjectStore
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: ceph.rook.io/v1
          kind: CephObjectStore
          metadata:
            name: "{{ rook_ceph_objectstore_name }}"
            namespace: "{{ rook_ceph_namespace }}"
          spec:
            metadataPool:
              replicated:
                size: "{{ rook_ceph_replica_size }}"
            dataPool:
              replicated:
                size: "{{ rook_ceph_replica_size }}"
            gateway:
              type: s3
              sslCertificateRef: ""
              port: "{{ rook_ceph_objectstore_gateway_port }}"
              instances: "{{ rook_ceph_objectstore_replicas }}"
              placement:
                topologySpreadConstraints: []
              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "500m"
                  memory: "1Gi"
      when: not (skip_kubernetes_operations or skip_helm_operations)
      tags: rook_objectstore

    - name: Create StorageClass for Ceph Object Buckets (optional)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: "{{ rook_ceph_objectstore_storage_class }}"
          provisioner: rook-ceph.ceph.rook.io/bucket
          parameters:
            objectStoreName: "{{ rook_ceph_objectstore_name }}"
            objectStoreNamespace: "{{ rook_ceph_namespace }}"
      when: not (skip_kubernetes_operations or skip_helm_operations)
      tags: rook_objectstore

    - name: Display CephObjectStore configuration (test mode)
      ansible.builtin.debug:
        msg:
          - "CephObjectStore would be deployed with:"
          - "ObjectStore Name: {{ rook_ceph_objectstore_name }}"
          - "Namespace: {{ rook_ceph_namespace }}"
          - "Gateway Port: {{ rook_ceph_objectstore_gateway_port }}"
          - "Replicas: {{ rook_ceph_objectstore_replicas }}"
          - "Storage Class: {{ rook_ceph_objectstore_storage_class }}"
      when: skip_kubernetes_operations or skip_helm_operations
      tags: rook_objectstore

  when: rook_ceph_enable_objectstore | bool
