# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Verify Helm is Installed
  block:
    - name: Check if Helm is available
      ansible.builtin.command: helm version --short
      register: helm_check
      changed_when: false
      failed_when: helm_check.rc != 0

  rescue:
    - name: Fail with message if Helm is not installed
      ansible.builtin.fail:
        msg: >
          Helm is required to install the Rook Ceph operator.
          Please ensure a Helm role is included before running this role.

  tags: rook_operator

- name: Ensure Namespace and Helm Repo Setup
  block:
    - name: Ensure rook-ceph namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ rook_ceph_namespace }}"
        state: present

    - name: Ensure Rook Helm repo is added
      kubernetes.core.helm_repository:
        name: rook-release
        repo_url: https://charts.rook.io/release

    - name: Update Helm repo cache
      ansible.builtin.command: helm repo update
      changed_when: false

  tags: rook_operator

- name: Install or Upgrade Rook Ceph Operator
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    release_namespace: "{{ rook_ceph_namespace }}"
    create_namespace: false
    values: "{{ rook_ceph_operator_values }}"
    chart_version: "{{ rook_ceph_operator_chart_version }}"
    state: present
    wait: true
  tags: rook_operator
