# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for mysql-operator
- name: Deploy MySQL Operator
  tags: [mysql-operator, database-mysql]
  when: mysql_install_operator | default(true)
  block:
    - name: Create mysql-operator directory
      ansible.builtin.file:
        path: "{{ mysql_operator_path }}"
        mode: "0744"
        state: directory

    - name: Add mysql-operator Helm repository
      kubernetes.core.helm_repository:
        name: mysql-operator
        repo_url: https://mysql.github.io/mysql-operator/
        state: present
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
      when: not (skip_kubernetes_operations or skip_helm_operations)

    - name: Deploy mysql-operator chart inside mysql-operator-system namespace
      kubernetes.core.helm:
        name: mysql-operator
        chart_ref: "{{ mysql_operator_chart_ref }}"
        chart_version: "{{ mysql_operator_chart_version }}"
        release_namespace: mysql-operator
        create_namespace: true
        update_repo_cache: true
        state: present
        wait: true
      environment:
        KUBECONFIG: "{{ kubectl_config }}"
      when: not (skip_kubernetes_operations or skip_helm_operations)

    - name: Display MySQL Operator configuration (test mode)
      ansible.builtin.debug:
        msg:
          - "MySQL Operator would be deployed with:"
          - "Chart: {{ mysql_operator_chart_ref }}"
          - "Version: {{ mysql_operator_chart_version }}"
          - "Namespace: mysql-operator"
          - "Repository: https://mysql.github.io/mysql-operator/"
      when: skip_kubernetes_operations or skip_helm_operations
