---
- name: Deploy CephFilesystem and StorageClass (optional)
  block:

    - name: Create CephFilesystem
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: ceph.rook.io/v1
          kind: CephFilesystem
          metadata:
            name: "{{ rook_ceph_filesystem_name }}"
            namespace: "{{ rook_ceph_namespace }}"
          spec:
            metadataPool:
              replicated:
                size: {{ rook_ceph_replica_size }}
            dataPools:
              - replicated:
                  size: {{ rook_ceph_replica_size }}
      tags: rook_filesystem

    - name: Create StorageClass for CephFS
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: "{{ rook_ceph_fs_storage_class }}"
          provisioner: rook-ceph.cephfs.csi.ceph.com
          parameters:
            clusterID: "{{ rook_ceph_namespace }}"
            fsName: "{{ rook_ceph_filesystem_name }}"
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: "{{ rook_ceph_namespace }}"
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: "{{ rook_ceph_namespace }}"
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: "{{ rook_ceph_namespace }}"
            csi.storage.k8s.io/fstype: ext4
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
      tags: rook_filesystem

    - name: Gather all StorageClasses for filesystem default cleanup
      community.kubernetes.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
      register: fs_storageclasses
      tags: rook_filesystem

    - name: Remove default annotation from other SCs (if setting fs as default)
      community.kubernetes.k8s:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: "{{ item.metadata.name }}"
        definition:
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: "false"
      loop: "{{ fs_storageclasses.resources }}"
      when:
        - rook_ceph_fs_make_default | bool
        - item.metadata.name != rook_ceph_fs_storage_class
        - item.metadata.annotations['storageclass.kubernetes.io/is-default-class'] | default('') == 'true'
      tags: rook_filesystem

    - name: Set CephFS StorageClass as default (if requested)
      community.kubernetes.k8s:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: "{{ rook_ceph_fs_storage_class }}"
        definition:
          metadata:
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
      when: rook_ceph_fs_make_default | bool
      tags: rook_filesystem

  when: rook_ceph_enable_filesystem | bool
