# SPDX-License-Identifier: GPL-3.0-or-later
---
# vars file for deploy-rke2-cluster
rke2_binary_root: "https://github.com/rancher/rke2/releases/download"
rke2_os: "linux"

# Common UFW rules for all nodes
ufw_rules_common:
  - port: "10250"
    proto: "tcp"
    comment: "RKE2 kubelet metrics"
  - port: "30000:32767"
    proto: "tcp"
    comment: "RKE2 NodePort port range"
  - port: "8472"
    proto: "udp"
    comment: "Canal CNI with VXLAN"
  - port: "9099"
    proto: "tcp"
    comment: "Canal CNI health checks"
  - port: "80"
    proto: "tcp"
    comment: "HTTP"
  - port: "443"
    proto: "tcp"
    comment: "HTTPS"

# Additional rules for controller nodes only
ufw_rules_controllers:
  - port: "6443"
    proto: "tcp"
    comment: "RKE2 Kubernetes API"
  - port: "9345"
    proto: "tcp"
    comment: "RKE2 Supervisor API"
  - port: "2379:2381"
    proto: "tcp"
    comment: "RKE2 etcd"
  - port: "8080"
    proto: "tcp"
    comment: "Traefik Dashboard"

# Supported operating systems
supported_distributions:
  - Ubuntu
  - Debian
  - Rocky
  - RedHat
  - Oracle
  - SLES
  - Amazon

# Minimum major versions
min_os_versions:
  Ubuntu: "20"
  Debian: "11"
  Rocky: "8"
  RedHat: "8"
  Oracle: "8"
  SLES: "15"
  Amazon: "2"
