# SPDX-License-Identifier: GPL-3.0-or-later
---
# vars file for deploy-rke2-cluster
rke2_binary_root: "https://github.com/rancher/rke2/releases/download"
rke2_os: "linux"

# Common UFW rules for all nodes
ufw_rules_common:
  - port: "10250"
    proto: "tcp"
    comment: "RKE2 kubelet metrics"
  - port: "30000:32767"
    proto: "tcp"
    comment: "RKE2 NodePort port range"
  - port: "8472"
    proto: "udp"
    comment: "Canal CNI with VXLAN"
  - port: "9099"
    proto: "tcp"
    comment: "Canal CNI health checks"
  - port: "80"
    proto: "tcp"
    comment: "HTTP"
  - port: "443"
    proto: "tcp"
    comment: "HTTPS"

# Additional rules for controller nodes only
ufw_rules_controllers:
  - port: "6443"
    proto: "tcp"
    comment: "RKE2 Kubernetes API"
  - port: "9345"
    proto: "tcp"
    comment: "RKE2 Supervisor API"
  - port: "2379:2381"
    proto: "tcp"
    comment: "RKE2 etcd"
  - port: "8080"
    proto: "tcp"
    comment: "Traefik Dashboard"

# Supported operating systems per official RKE2 support matrix
# https://www.suse.com/suse-rke2/support-matrix/all-supported-versions/rke2-v1-32/
supported_distributions:
  - Ubuntu
  - Rocky
  - RedHat
  - Oracle
  - SLES
  - openSUSE Leap
  - Amazon

# Minimum major versions per official support matrix
min_os_versions:
  Ubuntu: "20"           # 20.04, 22.04, 24.04, 25.04
  Rocky: "8"             # 8.7, 8.8, 8.9, 9.1, 9.2, 9.3, 9.4, 9.5
  RedHat: "8"            # RHEL 8.7, 8.8, 8.9, 9.1, 9.2, 9.3, 9.4, 9.5
  Oracle: "8"            # Oracle Linux 8.7, 8.8, 8.9, 9.1, 9.2, 9.3, 9.4, 9.5
  SLES: "15"             # SLES 15 SP3, SP4, SP5, SP6
  "openSUSE Leap": "15"  # openSUSE Leap 15.3, 15.4, 15.5, 15.6
  Amazon: "2"            # Amazon Linux 2, Amazon Linux 2023
