#!/usr/bin/env python3
"""Generate ``docs/variables.md`` from ``playbooks/group_vars/all.yaml``.

An inline ``# description`` trailing a top-level assignment is captured as the
variable's description. Standalone header comments are ignored. Types are
inferred from the parsed value.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE = REPO_ROOT / "playbooks" / "group_vars" / "all.yaml"
OUT = REPO_ROOT / "docs" / "variables.md"

# Top-level assignment with an optional inline comment:
#   name: value    # description
_ASSIGN = re.compile(
    r"^(?P<name>[a-zA-Z_][a-zA-Z0-9_]*):\s*[^\n#]*?(?:#\s*(?P<comment>.*))?\s*$"
)


def infer_type(value: object) -> str:
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if isinstance(value, list):
        return "list"
    if isinstance(value, dict):
        return "dict"
    return "str"


def format_default(value: object) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, str) and value == "":
        return '`""`'
    if isinstance(value, list):
        return f"`{value}`" if value else "`[]`"
    if isinstance(value, dict):
        return f"`{value}`" if value else "`{}`"
    return f"`{value}`"


def parse_descriptions(text: str) -> dict[str, str]:
    descs: dict[str, str] = {}
    for line in text.splitlines():
        if not line or line[0].isspace() or line.startswith("#") or line.startswith("---"):
            continue
        match = _ASSIGN.match(line)
        if not match:
            continue
        comment = match.group("comment")
        if comment:
            descs[match.group("name")] = comment.strip()
    return descs


def main() -> int:
    text = SOURCE.read_text()
    data = yaml.safe_load(text) or {}
    descs = parse_descriptions(text)

    rows = []
    for name in sorted(data.keys()):
        value = data[name]
        rows.append(
            {
                "name": name,
                "type": infer_type(value),
                "default": value,
                "description": descs.get(name, ""),
            }
        )

    header = [
        "# Variables",
        "",
        f"User-facing variables for the collection — {len(rows)} entries sourced from "
        "[`playbooks/group_vars/all.yaml`](../playbooks/group_vars/all.yaml).",
        "",
        "Generated by `scripts/gen_docs.py`. Do not edit directly.",
        "",
        "| Variable | Type | Default | Description |",
        "|---|---|---|---|",
    ]
    body = []
    for r in rows:
        default = format_default(r["default"]).replace("|", "\\|")
        desc = r["description"].replace("|", "\\|")
        body.append(f"| `{r['name']}` | {r['type']} | {default} | {desc} |")
    new = "\n".join(header + body) + "\n"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    old = OUT.read_text() if OUT.exists() else ""
    changed = new != old
    if changed:
        OUT.write_text(new)
    print(f"Variables: {len(rows)}; docs/variables.md changed: {changed}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
