# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Converge
  hosts: all
  become: true

  tasks:
    - name: Include deploy_rke2 role
      ansible.builtin.include_role:
        name: wolskinet.rke2_ansible.deploy_rke2
