# SPDX-License-Identifier: GPL-3.0-or-later
---
- name: Converge
  hosts: all
  become: true
  
  tasks:
    - name: Include minio_install role
      ansible.builtin.include_role:
        name: wolskinet.rke2_ansible.minio_install