---
home_path: /home/{{ ansible_user }}
traefik_domain: example
kubectl_config: "{{ home_path }}/.kube/config"
cert_manager_path: "{{ home_path }}/cert-manager"

minio_operator_path: "{{ home_path }}/minio-operator"
minio_operator_namespace: minio-operator

minio_tenant_path: "{{ home_path }}/minio-tenant"
minio_tenant_namespace: minio-tenant
minio_tenant_name: "minio"
# CSI driver can be "defaut" or "directpv-min-io"
minio_csi_driver_name: "directpv-min-io"
direct_pv_version: "4.1.5"

minio_root_user: "minio"
minio_root_password: "minio123"
minio_storage_class_standard: "EC:2"
minio_browser: "on"

console_access_key: "console"
console_secret_key: "console123"

minio_servers: 3
minio_volumes_per_server: 1
minio_storage_requests: "1Ti"