# SPDX-License-Identifier: GPL-3.0-or-later
---
# defaults file for minio_install

# General Configuration
home_path: /home/{{ ansible_user }}
traefik_domain: example

# Kubectl Options
kubectl_config: "{{ home_path }}/.kube/config"

# Cert-Manager Options
cert_manager_path: "{{ home_path }}/cert-manager"

minio_operator_path: "{{ home_path }}/minio-operator"
minio_operator_namespace: minio-operator

minio_tenant_path: "{{ home_path }}/minio-tenant"
minio_tenant_namespace: minio-tenant
minio_tenant_name: "minio"
# CSI driver can be "defaut" or "directpv-min-io"
minio_csi_driver_name: "directpv-min-io"
direct_pv_version: "4.1.5"

minio_root_user: "minio"
minio_root_password: "minio123"
minio_storage_class_standard: "EC:2"
minio_browser: "on"

console_access_key: "console"
console_secret_key: "console123"

minio_servers: 4
minio_volumes_per_server: 1
minio_capacity_per_tenant: "1Ti"

# Test mode configuration
test_mode: false
skip_kubernetes_operations: false
skip_helm_operations: false