---
# Recommended Workflow: Core RKE2 + Rancher Deployment
# Deploy the foundation cluster and Rancher, then manage additional apps via Rancher GUI
- name: Deploy RKE2 Cluster with Rancher Management
  hosts:
    - rke2
  # Include secrets if available (not required for CI/testing)
  vars:
    secrets_file: "/home/user/Ansible/inventory/group_vars/secrets.yaml"
  pre_tasks:
    - name: Include secrets if file exists
      ansible.builtin.include_vars: "{{ secrets_file }}"
      when: secrets_file is file
  become: false
  roles:
    # Install Helm on all nodes
    - role: wolskinet.rke2_ansible.helm_install
      become: false

    # Install RKE2 cluster on all nodes
    - role: wolskinet.rke2_ansible.deploy_rke2
      become: true

    # Install Rancher management platform (first controller only)
    - role: wolskinet.rke2_ansible.rancher_install
      when: inventory_hostname == (groups['controllers'] | first)
      become: false
      run_once: true
      tags: rancher

    # Optional: Automated storage deployment (if you prefer not to use Rancher GUI)
    # Remove these roles if you want to install storage via Rancher Apps & Marketplace
    # Longhorn - distributed block storage (OPTIONAL - can install via Rancher GUI)
    # - role: wolskinet.rke2_ansible.longhorn_install
    #   when: inventory_hostname == (groups['controllers'] | first)
    #   become: false
    #   run_once: true
    #   tags: longhorn

    # Rook/Ceph - distributed storage alternative (OPTIONAL - can install via Rancher GUI)
    # - role: wolskinet.rke2_ansible.rook_install
    #   when: inventory_hostname == (groups['controllers'] | first)
    #   become: false
    #   run_once: true
    #   tags: rook

    # Additional optional roles (consider managing via Rancher GUI instead):
