---
- name: Deploy RKE2 Cluster
  hosts:
    - rke2
  # Include secrets if available (not required for CI/testing)
  vars:
    secrets_file: "/home/{{ ansible_user }}/Ansible/inventory/group_vars/secrets.yaml"
  pre_tasks:
    - name: Include secrets if file exists
      include_vars: "{{ secrets_file }}"
      when: secrets_file is file
  become: false
  roles:
    # Install Helm on all nodes
    - role: helm_install
      become: false

    # Install RKE2 cluster on all nodes
    - role: deploy_rke2
      become: true

    # Install Rancher management platform (first controller only)
    - role: rancher_install
      when: inventory_hostname == (groups['controllers'] | first)
      become: false
      tags: rancher

    # Storage options - (first controller only)
    # Longhorn - distributed block storage
    - role: longhorn_install
      when: inventory_hostname == (groups['controllers'] | first)
      become: false
      tags: longhorn

    # Rook/Ceph - distributed storage alternative
    # - role: wolskinet.rke2_ansible.rook_install
    #   when: inventory_hostname == (groups['controllers'] | first)
    # become: false
    # tags: rook

    # MinIO - object storage
    # - role: wolskinet.rke2_ansible.minio_install
    #   when: inventory_hostname == (groups['controllers'] | first)
    # become: false
    # tags: minio

    # MySQL Operator - database operator
    # - role: wolskinet.rke2_ansible.mysql_operator
    #   when: inventory_hostname == (groups['controllers'] | first)
    # become: false
    # tags: mysql
