
- name: Deploy RKE2 Cluster
  hosts:
    - rke2
  vars_files:
    - /home/{{ ansible_user }}/Ansible/inventory/group_vars/secrets.yaml
  become: false
  roles:
    - name: wolskinet.rke2_ansible.deploy_rke2
      become: true
    - name: wolskinet.rke2_ansible.rancher_install
      when: inventory_hostname == (groups['servers'] | first)
      become: false
