---
- name: Deploy RKE2 Cluster
  hosts:
    - RKE2
  become: true
  collections:
    - wolskinet.rke2_ansible
  tasks:
    - name: Import roles
      ansible.builtin.import_role:
        name: wolskinet.rke2_ansible.deploy_rke2