#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy-rke2-cluster
- name: Prepare nodes and download RKE2
  ansible.builtin.include_tasks:
    file: prepare-nodes.yaml

- name: Install kube-vip manifest
  ansible.buitlin.include_tasks:
    file: kube-vip-manifest.yaml
  when: not kube_vip_noinstall

- name: Create directory for RKE2 config
  ansible.builtin.file:
    path: "/etc/rancher/rke2"
    state: directory
    mode: '0644'

- name: Create directory for RKE2 token
  ansible.builtin.file:
    path: "/var/lib/rancher/rke2/server"
    state: directory
    mode: '0644'

- name: Bootstrap first server
  ansible.builtin.include_tasks:
    file: initial-bootstrap.yaml
  when: inventory_hostname in groups['servers']

- name: Add additional RKE2 Servers
  ansible.builtin.include_tasks:
    file: add-servers.yaml
  when: inventory_hostname in groups['servers']

- name: Add additional RKE2 agents
  ansible.builtin.include_tasks:
    file: add-agents.yaml
  when: inventory_hostname in groups['agents']

- name: Install and configure metallb
  ansible.builtin.include_tasks:
    file: metallb.yaml
  when:  inventory_hostname in groups['servers'][0]