# SPDX-License-Identifier: GPL-3.0-or-later
---
# Remove NetworkManager per https://docs.rke2.io/install/methods
- name: Remove NetworkManager
  ansible.buiiltin.package:
    name: network-manager
    state: absent
  become: true

- name: Disable and stop firewalld if present
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  when: >
    "'firewalld.service' in ansible_facts.services
     and ansible_facts.services['firewalld.service'].state == 'running'"
  become: true

- name: Configure UFW rules
  ansible.builtin.include_task:
    file: prepare-nodes-ufw.yaml
  when: firewall == 'ufw'
