# SPDX-License-Identifier: GPL-3.0-or-later
---
# defaults file for rancher_install - user-customizable variables

# Most variables are defined in playbooks/group_vars/all.yaml
# Override individual variables here if needed for specific deployments

# Domain and environment configuration
# traefik_domain: "example"                    # Defined in group_vars/all.yaml
# letsencrypt_env: "production"                # Defined in group_vars/all.yaml
# cert_manager_email: "your_email@domain.com"  # Defined in group_vars/all.yaml
# traefik_dashboard_expose: false              # Defined in group_vars/all.yaml

# Component versions
# helm_version: "v3.18.4"                      # Defined in group_vars/all.yaml
# cert_manager_chart_version: "v1.18.2"        # Defined in group_vars/all.yaml
# traefik_chart_version: "37.0.0"              # Defined in group_vars/all.yaml
# rancher_chart_version: "2.11.3"              # Defined in group_vars/all.yaml

# Cloudflare API Token for Let's Encrypt DNS-01 challenge
# Maps from vault variable CF_TOKEN to role variable cf_token
# cf_token: "{{ CF_TOKEN | default('') }}"     # Defined in group_vars/all.yaml
