# SPDX-License-Identifier: GPL-3.0-or-later
---
home_path: /home/{{ ansible_user }}
traefik_domain: example
letsencrypt_env: production

kubectl_config: "{{ home_path }}/.kube/config"

# https://github.com/helm/helm/releases
helm_version: "v3.18.4"

cert_manager_chart_ref: jetstack/cert-manager
# https://github.com/cert-manager/cert-manager/releases
cert_manager_chart_version: v1.18.2
cert_manager_path: "{{ home_path }}/cert-manager"
cert_manager_email: your_email@your_domain.com

traefik_chart_ref: traefik/traefik
# https://github.com/traefik/traefik-helm-chart/releases
traefik_chart_version: 37.0.0
traefik_path: "{{ home_path }}/traefik"
traefik_dashboard_expose: false

# https://github.com/rancher/rancher/releases
rancher_chart_ref: rancher-stable/rancher
rancher_chart_version: 2.12.0
rancher_path: "{{ home_path }}/rancher"


