# SPDX-License-Identifier: GPL-3.0-or-later
---
home_path: /home/{{ ansible_user }}
traefik_domain: example

kubectl_config: "{{ home_path }}/.kube/config"

# https://github.com/helm/helm/releases
helm_version: v3.18.2

cert_manager_chart_ref: jetstack/cert-manager
# https://github.com/cert-manager/cert-manager/releases
cert_manager_chart_version: v1.15.0
cert_manager_path: "{{ home_path }}/cert-manager"
cert_manager_email: your_email@your_domain.com

traefik_chart_ref: traefik/traefik
# https://github.com/traefik/traefik-helm-chart/releases
traefik_chart_version: 36.0.0
traefik_path: "{{ home_path }}/traefik"

# https://github.com/rancher/rancher/releases
rancher_chart_ref: rancher/rancher
rancher_chart_version: 2.11.2
rancher_path: "{{ home_path }}/rancher"

longhorn_chart_ref: longhorn/longhorn
longhorn_chart_version: 1.9.0
longhorn_path: "{{ home_path }}/longhorn"