# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for teardown
- name: RKE2 Cluster Teardown
  tags: [cleanup-rke2, always]
  block:
    - name: Download RKE2 uninstaller
      ansible.builtin.shell: |
        set -o pipefail
        curl -sfL https://get.rke2.io | sh -
      become: true
      register: download_uninstaller_result
      changed_when: download_uninstaller_result.rc == 0
      failed_when: download_uninstaller_result.rc != 0

    - name: Run RKE2 uninstaller
      ansible.builtin.command:
        cmd: /usr/local/bin/rke2-uninstall.sh
      become: true
      register: uninstaller_result
      changed_when: uninstaller_result.rc == 0
      failed_when: false

- name: Configuration Files Cleanup
  tags: [cleanup-config, always]
  block:
    - name: Delete kubectl config and component directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ kubectl_config }}"
        - "{{ metallb_path }}"
        - "{{ cert_manager_path }}"
        - "{{ traefik_path }}"
        - "{{ rancher_path }}"
        - "{{ longhorn_path }}"
        - "{{ minio_operator_path }}"
        - "{{ minio_tenant_path }}"
        - "{{ mysql_operator_path }}"
      become: true

- name: Storage Components Cleanup
  tags: [cleanup-storage]
  become: true
  block:
    - name: Remove DirectPV binary
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.local/bin/kubectl-directpv
        state: absent

- name: Ensure UFW rules are removed for RKE2 controllers
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
    delete: true
  loop: "{{ ufw_rules_server }}"
  notify: Reload UFW
  when: inventory_hostname in groups['controllers']
  become: true

- name: Ensure UFW rules are removed for RKE2 agents
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
    delete: true
  loop: "{{ ufw_rules_agent }}"
  notify: Reload UFW
  when: inventory_hostname in groups['agents']
  become: true

- name: Ensure UFW rules are removed for CNI
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
    delete: true
  loop: "{{ ufw_rules_canal }}"
  notify: Reload UFW
  become: true

- name: Reboot System
  ansible.builtin.reboot:
