# SPDX-License-Identifier: GPL-3.0-or-later
---
# tasks file for teardown
- name: RKE2 Cluster Teardown
  tags: [cleanup-rke2, always]
  block:
    - name: Download RKE2 uninstaller
      ansible.builtin.shell: |
        set -o pipefail
        curl -sfL https://get.rke2.io | sh -
      args:
        executable: /bin/bash
      become: true
      register: download_uninstaller_result
      changed_when: download_uninstaller_result.rc == 0
      failed_when: download_uninstaller_result.rc != 0

    - name: Run RKE2 uninstaller
      ansible.builtin.command:
        cmd: /usr/local/bin/rke2-uninstall.sh
      become: true
      register: uninstaller_result
      changed_when: uninstaller_result.rc == 0
      failed_when: false

- name: Configuration Files Cleanup
  tags: [cleanup-config, always]
  block:
    - name: Delete kubectl config and component directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ kubectl_config }}"
        - "{{ metallb_path }}"
        - "{{ cert_manager_path }}"
        - "{{ traefik_path }}"
        - "{{ rancher_path }}"
        - "{{ longhorn_path }}"
        - "{{ mysql_operator_path }}"
      become: true

- name: Storage Components Cleanup
  tags: [cleanup-storage]
  become: true
  block:
    - name: Placeholder for storage cleanup tasks
      ansible.builtin.debug:
        msg: "No storage-specific cleanup tasks currently defined"

- name: Remove UFW rules for all nodes
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
    delete: true
  loop: "{{ ufw_rules_common }}"
  notify: Reload UFW
  when: firewall == 'ufw'
  become: true

- name: Remove UFW rules for controllers
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
    delete: true
  loop: "{{ ufw_rules_controllers }}"
  notify: Reload UFW
  when: >
    firewall == 'ufw' and
    inventory_hostname in groups['controllers']
  become: true

- name: Reboot System
  ansible.builtin.reboot:
