#SPDX-License-Identifier: MIT-0
---
# tasks file for teardown
- name: Download RKE2 uninstaller
  ansible.builtin.shell:  curl -sfL https://get.rke2.io | sh -
  become: true

- name: Run RKE2 uninstaller
  ansible.builtin.command:
    cmd: /usr/local/bin/rke2-uninstall.sh
  become: true

- name: Delete spec files 
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ metallb_path }}"
    - "{{ kubectl_config }}"
    - "{{ cert_manager_path }}"
    - "{{ traefik_path }}"
    - "{{ rancher_path }}"
    - "{{ minio_operator_path }}"
    - "{{ minio_tenant_path }}"
  become: true

- name: Remove directpv
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.local/bin/kubectl-directpv
    state: absent
  become: true
        
- name: Ensure UFW rules are removed for RKE2 controllers
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
    delete: true
  loop: "{{ ufw_rules_server }}"
  notify: Reload UFW
  when: inventory_hostname in groups['controllers']
  become: true

- name: Ensure UFW rules are removed for RKE2 agents
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
    delete: true
  loop: "{{ ufw_rules_agent }}"
  notify: Reload UFW
  when: inventory_hostname in groups['agents']
  become: true

- name: Ensure UFW rules are removed for CNI
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
    delete: true
  loop: "{{ ufw_rules_canal }}"
  notify: Reload UFW
  become: true

- name: Reboot System
  ansible.builtin.reboot: