# SPDX-License-Identifier: GPL-3.0-or-later
# Template test mode variables for role defaults/main.yml
# Add these variables to enable test mode support

# Test mode configuration - allows roles to skip operations that don't work in containers
---
test_mode: false

# Skip flags for specific operations (customize per role)
skip_binary_installation: false      # Skip downloading/installing actual binaries
skip_service_management: false       # Skip systemctl operations
skip_firewall_configuration: false   # Skip firewall rules
skip_networking_configuration: false # Skip network interface changes
skip_kubernetes_operations: false    # Skip kubectl/k8s API calls
skip_helm_operations: false          # Skip helm repository/chart operations
skip_external_dependencies: false    # Skip external service dependencies

# Mock binary paths (for test mode verification)
mock_binary_dir: /usr/local/bin

# Kubernetes testing pattern:
# Use these variables in tasks like:
# when: not (skip_kubernetes_operations or skip_helm_operations)
